@startuml
skinparam backgroundColor #EEEBDC
skinparam activity {
    BorderColor DarkSlateGray
    BorderThickness 2
    BackgroundColor LightYellow
}

start
:Persiapan;
:Melakukan riset pekerjaan;
:nemu di akun sosial;
:Menyesuaikan CV dan surat lamaran;
:Melamar pekerjaan;
if (Diterima?) then (ya)
    :Wawancara;
    if (Lulus?) then (ya)
        :Tawar gaji;
        :Mulai bekerja;
    else (tidak)
        :Lakukan evaluasi diri;
        stop
    endif
else (tidak)
    :Lakukan follow-up;
endif
:Bagikan pengalaman dan keterampilan;
:Gunakan jejaring sosial dan situs web;
:Ikuti pelatihan dan kursus;
:Perbaharui CV dan portofolio;
:Kembangkan keterampilan baru;
stop
@enduml